vich_uploader:
    db_driver: orm

    mappings:
        miniature:
            uri_prefix: /Images/miniatures
            upload_destination: '%kernel.project_dir%/public/Images/miniatures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        profil:
            uri_prefix: /Images/ProfilImg
            upload_destination: '%kernel.project_dir%/public/Images/ProfilImg'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
